// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-menu-items.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-menu-items.ts
var list_menu_items_default = defineTool({
  name: "list_menu_items",
  title: "List menu items",
  description: "List Kookoos menu items, optionally filtered by category slug or availability.",
  inputSchema: {
    category_slug: z.string().optional().describe("Optional category slug to filter by."),
    available_only: z.boolean().optional().describe("Only return items marked available."),
    limit: z.number().int().min(1).max(200).optional().describe("Max items to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category_slug, available_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("menu_items").select("id,name,description,price,category_id,is_available,image_url,categories(slug,name)").limit(limit ?? 50);
    if (available_only) query = query.eq("is_available", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const filtered = category_slug ? (data ?? []).filter((row) => row.categories?.slug === category_slug) : data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(filtered) }],
      structuredContent: { items: filtered }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_my_orders_default = defineTool2({
  name: "list_my_orders",
  title: "List my orders",
  description: "List orders belonging to the signed-in Kookoos user, most recent first.",
  inputSchema: {
    status: z2.string().optional().describe("Optional status filter (pending, preparing, ready, etc.)."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max orders to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("orders").select("id,total_amount,status,delivery_address,phone,notes,created_at,order_items(item_name,item_price,quantity)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_order_default = defineTool3({
  name: "get_order",
  title: "Get order",
  description: "Fetch a single Kookoos order (including its items) by order ID. RLS ensures only the owning user or staff can read it.",
  inputSchema: {
    order_id: z3.string().uuid().describe("The order UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("orders").select("id,user_id,total_amount,status,delivery_address,phone,notes,created_at,order_items(item_name,item_price,quantity)").eq("id", order_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Order not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/create-order.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var create_order_default = defineTool4({
  name: "create_order",
  title: "Create order",
  description: "Place a new Kookoos order for the signed-in user with the given items, phone, and delivery address.",
  inputSchema: {
    phone: z4.string().min(6).describe("Contact phone number for the order."),
    delivery_address: z4.string().min(3).describe("Full delivery address."),
    notes: z4.string().optional().describe("Optional special instructions."),
    items: z4.array(
      z4.object({
        name: z4.string().min(1),
        price: z4.number().nonnegative(),
        quantity: z4.number().int().min(1)
      })
    ).min(1).describe("Line items to include in the order.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ phone, delivery_address, notes, items }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const total = items.reduce((sum, i) => sum + i.price * i.quantity, 0);
    const { data: order, error: orderError } = await sb.from("orders").insert({
      user_id: ctx.getUserId(),
      total_amount: total,
      delivery_address,
      phone,
      notes: notes ?? null,
      status: "pending"
    }).select().single();
    if (orderError || !order) {
      return { content: [{ type: "text", text: orderError?.message ?? "Failed to create order" }], isError: true };
    }
    const rows = items.map((i) => ({
      order_id: order.id,
      item_name: i.name,
      item_price: i.price,
      quantity: i.quantity
    }));
    const { error: itemsError } = await sb.from("order_items").insert(rows);
    if (itemsError) {
      return { content: [{ type: "text", text: itemsError.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Order ${order.id} placed. Total: TSh ${total.toLocaleString()}` }],
      structuredContent: { order_id: order.id, total_amount: total, status: order.status }
    };
  }
});

// src/lib/mcp/tools/list-stores.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_stores_default = defineTool5({
  name: "list_stores",
  title: "List stores",
  description: "List Kookoos store locations with addresses and contact info.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("stores").select("*");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { stores: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cvrzxjqwokstjusoauec";
var mcp_default = defineMcp({
  name: "kookoos-mcp",
  title: "Kookoos",
  version: "0.1.0",
  instructions: "Tools for Kookoos, a Tanzanian street-food restaurant. Browse the menu, view store locations, place delivery orders, and check your own order history. All order tools act as the signed-in Kookoos user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_menu_items_default, list_stores_default, list_my_orders_default, get_order_default, create_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
