// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruqaadoukbydmhjooybj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cWFhZG91a2J5ZG1oam9veWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MjQ1MzQsImV4cCI6MjA5OTEwMDUzNH0.ujtclZ4aqwqWI_VhYuaHV34KeJjSb7VlsTsG858259k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});